<?php

/**
 * @file
 * Contains hello.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\editor\Entity\Editor;

/**
 * Implements hook_help().
 */
function hello_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hello module.
    case 'help.page.hello':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hello world KRM') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function hello_theme() {
  return [
    'hello' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_install().
 */
function hello_install() {
  
}

/**
 * Implements hook_editor_js_settings_alter
 */
function hello_editor_js_settings_alter(array &$settings) {
  //Todo: make skillcourse a constant somewhere.
  //Todo: create skillcourse format on install, and set it up.
  if (empty($settings['editor']['formats']['skillcourse'])) {
    return;
  }
  $skillcourseSettings = &$settings['editor']['formats']['skillcourse']['editorSettings'];
  //Use brs for enter key.
  $skillcourseSettings['enterMode'] = 2;
  //Don't encode entities?
  $skillcourseSettings['entities'] = FALSE;
  //Remove plugins that implement context menu.
  //See https://www.drupal.org/project/ckeditor_browser_context_menu
  $skillcourseSettings['removePlugins'] = 'contextmenu,tabletools,tableresize';
  $skillcourseSettings['disableNativeSpellChecker'] = false;
}

function hello_ckeditor_css_alter(array &$css, Editor $editor) {
  //Add CSS to change CKEditor to monospace font.
  $css[] = drupal_get_path('module', 'hello') . '/css/ckeditor.css';
}



